import{a as P,S as q,i as n}from"./assets/vendor-C9vNCoLC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",M="50342866-da1b32c712fb25d761b3cb22e";async function m(s,t){const i={key:M,q:s,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await P.get(B,{params:i})).data}catch(o){throw console.error("Error fetching images:",o),o}}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more-btn"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(s){const t=s.map(({webformatURL:i,largeImageURL:o,tags:e,likes:r,views:l,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a href="${o}">
        <img src="${i}" alt="${e}" />
      </a>
      <div>
        <ul class="info">
        <li class="info-item"><h4>Likes:</h4><p>${r}</p></li>
        <li class="info-item"><h4>Views:</h4><p>${l}</p></li>
        <li class="info-item"><h4>Comments:</h4><p>${w}</p></li>
        <li class="info-item"><h4>Downloads:</h4><p>${S}</p></li>
</ul>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function x(){h.innerHTML=""}function y(){f.classList.add("is-visible")}function b(){f.classList.remove("is-visible")}function L(){g.classList.remove("is-visible")}function d(){g.classList.add("is-visible")}const v=document.querySelector(".form"),E=v.elements["search-text"],O=document.querySelector(".load-more-btn");let u,a=0,c=0;const R=15;v.addEventListener("submit",async s=>{if(s.preventDefault(),u=E.value.trim(),a=1,!u){n.warning({message:"Please enter a search term."});return}x(),y();try{const t=await m(u,a);if(t.hits.length===0){d(),n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3});return}p(t.hits),c=Math.ceil(t.totalHits/R),c>a?L():d(),a===c&&n.success({message:"We`re sorry, but you`ve reached the end of search results.",position:"topRight",timeout:3e3})}catch{n.error({message:"Something went wrong. Please try again later."})}finally{b()}console.log(c),s.target.reset()});O.addEventListener("click",async s=>{a+=1,y();try{const t=await m(u,a);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3});return}p(t.hits),c>a?L():d(),a===c&&n.success({message:"We`re sorry, but you`ve reached the end of search results.",position:"topRight",timeout:3e3});const i=document.querySelector(".gallery-item");if(i){const o=i.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}catch{n.error({message:"Something went wrong. Please try again later."})}finally{b()}});
//# sourceMappingURL=index.js.map
